### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by amchess** [nodchip/Stockfish#64]
The last code doesn't build with the latest MinGW 8.1.0 on Windows.
The problem is the line
#include <filesystem>
in main.cpp

**Comment by nodchip** [comment]
Thank you for posting an issue.
Could you please try compile on MSYS2 with g++ 10.1.0?

**Comment by amchess** [comment]
I suppose it works, but I don't use it because it seems to me yet msys1.0 gives better executables.

**Comment by nodchip** [comment]
I see.
I and some people from Stockfish community are working on integrating NNUE in the official branch of Stockfish. I'm stopping modifying my repository to avoid interferes with those works. Once the part of NNUE is integrated in the official branch, could you please create another issue on the official Stockfish github repository?

**Comment by amchess** [comment]
Even the target learn-nnue has the same problem:
I tried to build this target with MinGW 8.1.0 and the following command:
mingw32-make nnue-learn ARCH=x86-64-bmi2 COMP=mingw CXX=x86_64-w64-mingw32-g++ -j %Number_Of_Processors%

Before it asked cblas.h library and I added it.
After there is the following error (and some others after):
In file included from C:/MinGW/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/filesystem:37,
                 from learn/learner.cpp:18:
C:/MinGW/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/bits/fs_path.h: In member function 'std::filesystem::cxx11::path& std::filesystem::cxx11::path::operator/=(const std::filesystem::cxx11::path&)':
C:/MinGW/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/bits/fs_path.h:237:47: error: no match for 'operator!=' (operand types are 'std::filesystem::cxx11::path' and 'std::filesystem::cxx11::path')
    || (p.has_root_name() && __p.root_name() != root_name()))

**Comment by amchess** [comment]
> 
> 
> I see.
> I and some people from Stockfish community are working on integrating NNUE in the official branch of Stockfish. I'm stopping modifying my repository to avoid interferes with those works. Once the part of NNUE is integrated in the official branch, could you please create another issue on the official Stockfish github repository?

Yes, where I have to put it?
Thanks

**Comment by nodchip** [comment]
I will let you know after the first stage of the integration is done.

**Comment by amchess** [comment]
thanks

**Comment by nodchip** [comment]
NNUE has been merged into the official Stockfish.
https://github.com/official-stockfish/Stockfish/commit/84f3e867903f62480c33243dd0ecbffd342796fc
Could you please ask about this issue in the official Stockfish respository?  I will close this issue.
