### ISSUE TITLE
Stockfish nnue with learn fails to compile on Ubuntu 18.04 due to a missing declaration

### ISSUE THREAD

**Issue by hero2017** [nodchip/Stockfish#92]
learn/learner.cpp:959:22: error: ‘INT_MIN’ was not declared in this scope
  959 |  int search_depth2 = INT_MIN;
      |                      ^~~
learn/learner.cpp:87:1: note: ‘INT_MIN’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’?
   86 | #include "../nnue/evaluate_nnue_learner.h"
  +++ |+#include <climits>
   87 | #include <shared_mutex>
...
make[1]: *** [<builtin>: learner.o] Error 1

The fix is to do just what it says; insert a new line in learn/learner.cpp after line 86: `#include <climits>` (thanks nodchip)

I'm not sure if this is specific to Ubuntu 18.04 and gcc v10.x but probably if we're defining something in header <climits> then we should declare it.

Please see if it makes sense to add this declaration to learner.cpp so Ubuntu users so Ubuntu users don't have to always add this fix for the current release and possibly future releases. Thanks in advance.

**Comment by nodchip** [comment]
Thank you for reporting an issue.  Could you please create a pull request to fix it?  Currently a regression test to release a new binary set is on going.  I will merge your pull request after it is finished.
